### ISSUE TITLE
Validating TEAmacroeconap fails

### ISSUE THREAD

**Issue by philschatz** [openstax/cnx-easybake#85]
This occurred while running `./script/diff-book TEAmacroeconap` on https://github.com/Connexions/cnx-recipes/pull/366 (with `master` merged in).

Hmm, maybe this should belong in cnx-epub. Is this a validation error or a bug? The fact that it's a stack trace seems to indicate a bug.

# Stack Trace

```
Traceback (most recent call last):
  File "/Users/phil/github/cnx/cnx-recipes/venv/bin/cnx-epub-validate-collated", line 11, in <module>
    load_entry_point('cnx-epub', 'console_scripts', 'cnx-epub-validate-collated')()
  File "/Users/phil/github/cnx/cnx-recipes/venv/src/cnxepub/cnxepub/scripts/collated_single_html/main.py", line 49, in main
    binder = reconstitute(args.collated_html)
  File "/Users/phil/github/cnx/cnx-recipes/venv/src/cnxepub/cnxepub/collation.py", line 51, in reconstitute
    return adapt_single_html(xhtml)
  File "/Users/phil/github/cnx/cnx-recipes/venv/src/cnxepub/cnxepub/adapters.py", line 359, in adapt_single_html
    _adapt_single_html_tree(binder, body[0], nav_tree, top_metadata=metadata)
  File "/Users/phil/github/cnx/cnx-recipes/venv/src/cnxepub/cnxepub/adapters.py", line 472, in _adapt_single_html_tree
    child.xpath('./*[@data-type="metadata"]')[0])
  File "/Users/phil/github/cnx/cnx-recipes/venv/src/cnxepub/cnxepub/html_parsers.py", line 84, in parse_metadata
    return parser()
  File "/Users/phil/github/cnx/cnx-recipes/venv/src/cnxepub/cnxepub/html_parsers.py", line 118, in __call__
    return self.metadata
  File "/Users/phil/github/cnx/cnx-recipes/venv/src/cnxepub/cnxepub/html_parsers.py", line 138, in metadata
    "A value for '{}' could not be found.".format(key))
ValueError: A value for 'title' could not be found.
./script/bake-book: ERROR: could not run [cnx-epub-validate-collated ./data/TEAmacroeconap-baked.xhtml]
./script/diff-book: ERROR: could not run [./script/bake-book TEAmacroeconap --use-repeatable-ids]
```

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
